version: 2
sources:
  - name: raw
    schema: raw
    tables:
      - name: customer
        columns:
          - name: customer_id
            data_tests: [unique, not_null]
      - name: subscription_period
        columns:
          - name: period_id
            data_tests: [unique, not_null]
          - name: customer_id
            data_tests:
              - not_null
              - relationships:
                  arguments:
                    to: source('raw', 'customer')
                    field: customer_id
      - name: calendar
        columns:
          - name: month
            data_tests: [unique, not_null]
